spring:
  datasource:
    url: jdbc:mariadb://43.202.13.182:3306/bizbazaar
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    # Hibernate 6.x에서 MariaDB와 호환되는 다이얼렉트 사용
    database-platform: org.hibernate.dialect.MariaDBDialect  # MariaDBDialect로 수정
    hibernate:
      ddl-auto: update  # 테이블 자동 생성 및 갱신 설정
    show-sql: true  # SQL 로그 출력